username: m.ali.azeem84@gmail.com
password: Innovapath@1

phone_number: (415) 818-4132

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'

role_type: ML

positions:
- ML Engineer 
- Gen AI Engineer
- LLM Engineer




locations:
- Bay Area,CA
- USA, Remote

roletype:
- 1 #onsite
- 2 #remote
- 3 #hybrid


salary: 180,000
rate: 80

uploads:
  Resume: Resumes\Ali_azeem.pdf

# uploads:
#   Resume:Resumes\Ali Azeem.pdf

  # Cover Letter: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cl.pdf
  #Photo: # PATH TO photo
#Male or Female
gender: Male


output_filename:
- I:\IP-Codebases\LinkedInAutomation\OUTPUT.csv

blacklist:
- Workday
- Lending Club
- Rally Health 
- Autodesk.

experience_level:
  - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  - 4 # Director
  - 5 # Executive
  - 6 # Internship