username: anr.kpk@gmail.com
password: Innova@23
phone_number: (469) 480-3708

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'

role_type: ML
positions:
- Machine learning Engineer
- gen AI



locations:
- Dallas, TX
- Remote,USA

roletype:
- 2 #remote
- 1 #onsite
- 3 #hybrid


salary: 160,000
rate: 60
# --------- Optional Parameters -------
uploads:
  Resume: Resumes/Narsimlu.pdf
  # Cover Letter: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cl.pdf
  #Photo: # PATH TO photo
#Male or Female
gender: Male


output_filename:
- I:\IP-Codebases\LinkedInAutomation\OUTPUT.csv

blacklist:
-  CitiCorp Services India
-  Virtusa Consultancy Services
# Company names you want to ignore

experience_level:
  - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  - 4 # Director
  - 5 # Executive
  - 6 # Internship