username: tsarojni28@gmail.com
password: Whitebox123
phone_number: (540) 709-1021

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'
role_type: UI


positions:
- FrontEnd Developer
- Full stack Developer
- Reactjs
- UI developer
- Web Developer


locations:
- Seattle,Washington

roletype:
- 1 #onsite
- 2 #remote
- 3 #hybrid


salary: 150,000
rate: 60
# --------- Optional Parameters -------
uploads:
  Resume: Resumes/Sarojni_Tripathi.pdf
  # Cover Letter: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cl.pdf
  #Photo: # PATH TO photo
#Male or Female
gender: Female


output_filename:
- I:\IP-Codebases\LinkedInAutomation\OUTPUT.csv

blacklist:
- Bank of The West
- Applied Materials
- Best Buy
- Tenet Healthcare
- United Airlines
experience_level:
  - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  - 4 # Director
  - 5 # Executive
  - 6 # Internship