username: smitabhosale906@gmail.com
password: Innovapath1
phone_number: (331) 240-1099

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'
role_type: QA


positions:
- SDET 
- Automation
- QA Engineer
- QA Analyst



locations:
- Naperville,IL

roletype:
- 1 #onsite
- 2 #remote
- 3 #hybrid


salary: 150,000
rate: 55


uploads:
  Resume: Resumes/Smita_Bhosale.pdf
  # Cover Letter: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cl.pdf
  #Photo: # PATH TO photo
#Male or Female
gender: Female


output_filename:
- I:\IP-Codebases\LinkedInAutomation\OUTPUT.csv

blacklist:
- Walgreens
- Citibank
- Advocate health care
- PS International Info services

experience_level:
  - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  - 4 # Director
  - 5 # Executive
  - 6 # Internship