username: srutej.kodiganti@gmail.com
password: srutejkInnovapath1
phone_number: +1 (770) 282-9950

profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'

role_type: ML

positions:
- Machine learning Engineer
- gen AI



locations:
- USA

roletype:
- 1 #onsite
- 2 #remote
- 3 #hybrid


salary: 160,000
rate: 60
# --------- Optional Parameters -------
uploads:
  Resume: Resumes/srutej_resume.pdf
  # Cover Letter: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cl.pdf
  #Photo: # PATH TO photo
#Male or Female
gender: Male


output_filename:
- I:\IP-Codebases\LinkedInAutomation\OUTPUT.csv

blacklist:
- 
# Company names you want to ignore

experience_level:
  - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  - 4 # Director
  - 5 # Executive
  - 6 # Internship