username: Swathika.kalyan88@gmail.com
password: Innovapath1
phone_number: 9255791278


profile_path: '' #can be empty, will default to 'C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default'

role_type: ML

positions:
- Machine Learning Engineer
- Generative AI
- LLM Engineer



locations:
- CA ,USA
- remote,USA

roletype:
- 1 #onsite
- 2 #remote
- 3 #hybrid


salary: 180,000
rate: 70
# --------- Optional Parameters -------
uploads:
  Resume: Resumes/Swathika_resume.pdf
  # Cover Letter: /Users/steven/Desktop/LinkedIn-Easy-Apply-Bot/cl.pdf
  #Photo: # PATH TO photo
#Male or Female
gender: Female


output_filename:
- I:\IP-Codebases\LinkedInAutomation\OUTPUT.csv

blacklist:
# - # Company names you want to ignore
- Lucid Motors
- Talent Screen
- United HealthCare Services, Inc
- E-Trade


experience_level:
  - 1 # Entry level
  - 2 # Associate
  - 3 # Mid-Senior level
  - 4 # Director
  - 5 # Executive
  - 6 # Internship
